### ISSUE TITLE
Support client and server installations

### ISSUE THREAD

**Issue by danielsreichenbach** [kogitoapp/puppet-minio#1]
After initial deployments using the module we figured that just provisioning a Minio storage is nice but without being able to provision buckets it is not possible to instantly get a practical use out of this.

Thus we want to extend the module so that it

* installs and configures Minio server,
* installs and configures the Minio command line client(!)

### Tasks

* refactoring recipes to generic ones calling server and client recipes in order,
* produce dedicated recipes for client
* move existing server handling to `minio:server`

### Know issues

This might introduce a BC break as we require versions and checksums for both client and server deployment.

**Comment by ZloeSabo** [comment]
Can I close this now?

**Comment by attachmentgenie** [comment]
imho this is now implemented in 1.1.2

**Comment by danielsreichenbach** [comment]
Yeah, that can be closed finally :smile:
