### ISSUE TITLE
Current implementation doesnt support distributed mode

### ISSUE THREAD

**Issue by attachmentgenie** [kogitoapp/puppet-minio#17]
## Affected Puppet, Ruby, OS and module versions/distributions

- Module version: HEAD:master

## How to reproduce (e.g Puppet code you use)

try to setup a distributed minio platform using the [official tutorial](https://docs.min.io/docs/distributed-minio-quickstart-guide.html)

`class { '::minio': storage_root => 'http://192.168.50.4{2...5}:9090/var/lib/minio' }`

## What are you seeing

> ==> file01: Notice: Compiled catalog for file01.storage.vagrant in environment production in 0.58 seconds
==> file01: Error: Parameter path failed on File[http://192.168.50.4{2...5}:9090/var/lib/minio]: File paths must be fully qualified, not 'http://192.168.50.4{2...5}:9090/var/lib/minio' (file: /tmp/vagrant-puppet/environments/production/modules/minio/manifests/install.pp, line: 85)

## What behaviour did you expect instead

Have some form of feature switch that allows us to not manage the storage_root or an additional parameter (e.g distributed_storage_root) that if set gets passed to the service file instead of the storage_root

**Comment by ZloeSabo** [comment]
Hey @attachmentgenie,
I've added support for erasure coding and distributed deployments in `1.1.2`. You could define your distributed deployment with `MINIO_DEPLOYMENT_DEFINITION` environment variable. Now the `storage_root` also accepts both individual path and an array of paths in case you need multiple storages for erasure coding.

Could you please verify if those changes enable your use case?

**Comment by attachmentgenie** [comment]
I ll have a look and test this out, thanks. The PR looks good already

**Comment by attachmentgenie** [comment]
@ZloeSabo i just updated my test nodes to use your improvements , they work very well thank you
